// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC42fahXHp_wLZSehl5Gtz_W5_J8erKDXA',
    appId: '1:35619894528:web:69e63a53e7af73f2f6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    authDomain: 'lang-words.firebaseapp.com',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
    measurementId: 'G-S70Q06GB54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBivQmqCIyEECTW5hdKgyukVPsTKh_Erss',
    appId: '1:35619894528:android:2da7881b387e73abf6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcRQ6KWxigo4SoSXFjj6rGDc5PtUZ5hw',
    appId: '1:35619894528:ios:1d21f70d2f19e432f6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
    iosClientId: '35619894528-6rrskd3q5hot30f5osqc72i7nfg6q1kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.langWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcRQ6KWxigo4SoSXFjj6rGDc5PtUZ5hw',
    appId: '1:35619894528:ios:1d21f70d2f19e432f6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
    iosClientId: '35619894528-6rrskd3q5hot30f5osqc72i7nfg6q1kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.langWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC42fahXHp_wLZSehl5Gtz_W5_J8erKDXA',
    appId: '1:35619894528:web:69e63a53e7af73f2f6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    authDomain: 'lang-words.firebaseapp.com',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
    measurementId: 'G-S70Q06GB54',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC42fahXHp_wLZSehl5Gtz_W5_J8erKDXA',
    appId: '1:35619894528:web:ea3d84c92af3fb42f6afe5',
    messagingSenderId: '35619894528',
    projectId: 'lang-words',
    authDomain: 'lang-words.firebaseapp.com',
    databaseURL: 'https://lang-words.firebaseio.com',
    storageBucket: 'lang-words.appspot.com',
    measurementId: 'G-J5HZ8LWPLS',
  );
}
