// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyo4snOiMtmji8L9Ol1IJQkuk8gjfCWs',
    appId: '1:485014055027:web:12d74e81de185051cba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    authDomain: 'lang-word-dev.firebaseapp.com',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHoH2wm6DpjeGYrETsP3kuLQWiG2tD1Mg',
    appId: '1:485014055027:android:beb10926cea8355ccba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkp8ireeCc3obhpEBmobiIiMwNSOA_vY',
    appId: '1:485014055027:ios:a9d2e6527f6fcabecba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
    iosClientId: '485014055027-bl66r2qqn9ak0muqd4h251g73joja49t.apps.googleusercontent.com',
    iosBundleId: 'com.example.langWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkp8ireeCc3obhpEBmobiIiMwNSOA_vY',
    appId: '1:485014055027:ios:a9d2e6527f6fcabecba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
    iosClientId: '485014055027-bl66r2qqn9ak0muqd4h251g73joja49t.apps.googleusercontent.com',
    iosBundleId: 'com.example.langWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsyo4snOiMtmji8L9Ol1IJQkuk8gjfCWs',
    appId: '1:485014055027:web:447cd98e960192becba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    authDomain: 'lang-word-dev.firebaseapp.com',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCsyo4snOiMtmji8L9Ol1IJQkuk8gjfCWs',
    appId: '1:485014055027:web:2558043ea5474abccba206',
    messagingSenderId: '485014055027',
    projectId: 'lang-word-dev',
    authDomain: 'lang-word-dev.firebaseapp.com',
    databaseURL: 'https://lang-word-dev.firebaseio.com',
    storageBucket: 'lang-word-dev.appspot.com',
  );
}
