// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:25d1183dd139119a0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBZPQCHN4Us5XS_F3wx3vcink1K0QpLA',
    appId: '1:436458077646:android:6d1d0625fe17b4280fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPIdndfB7TY4D1MgPKTOlXqZ4nxnAAXlA',
    appId: '1:436458077646:ios:9f5d0d324a49832c0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
    iosClientId: '436458077646-2dnoqo1d9ea251hd2tgnmvo1i8amvjdu.apps.googleusercontent.com',
    iosBundleId: 'app.web.langWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPIdndfB7TY4D1MgPKTOlXqZ4nxnAAXlA',
    appId: '1:436458077646:ios:9f5d0d324a49832c0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
    iosClientId: '436458077646-2dnoqo1d9ea251hd2tgnmvo1i8amvjdu.apps.googleusercontent.com',
    iosBundleId: 'app.web.langWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:23be7f88057283b80fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:b40f5dc52155bb270fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );
}
