// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:90b41091a6a31aed0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBZPQCHN4Us5XS_F3wx3vcink1K0QpLA',
    appId: '1:436458077646:android:6b2f5ed29cec209a0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPIdndfB7TY4D1MgPKTOlXqZ4nxnAAXlA',
    appId: '1:436458077646:ios:7214224eba7d7b5f0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
    iosClientId: '436458077646-ftetpso5nh378h57okdc871iai7ggh6o.apps.googleusercontent.com',
    iosBundleId: 'app.web.langWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPIdndfB7TY4D1MgPKTOlXqZ4nxnAAXlA',
    appId: '1:436458077646:ios:7214224eba7d7b5f0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
    iosClientId: '436458077646-ftetpso5nh378h57okdc871iai7ggh6o.apps.googleusercontent.com',
    iosBundleId: 'app.web.langWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:2fe873ed91eee8cd0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyABiTtEv4Ly-oX16dJJb5JXX9hfSjc9jB4',
    appId: '1:436458077646:web:b76e9ac222561d7c0fbf9f',
    messagingSenderId: '436458077646',
    projectId: 'lang-words-stag',
    authDomain: 'lang-words-stag.firebaseapp.com',
    databaseURL: 'https://lang-words-stag-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lang-words-stag.appspot.com',
  );
}
